# @file	  instructions.py
# @author Garfield A. Lewis <garfield.lewis@lzlabs.com>
# @brief  Create a dictionary of zOS instructions based on their Mnemonic.
#        
# https://www.ibm.com/support/libraryserver/download/dz9zr006.pdf
#
import sys
import os

# Add the current path to the system path so that the subsequent import will
# find my external libraries.
if sys.path[0] != '/opt/lzlabs/debug/gdb/apis':
   sys.path.insert( 0, '/opt/lzlabs/debug/gdb/apis' )

from decoder import *

# @def   zos_2byte_mnomics
# @brief A dictionary of zOS 2 byte Mnemonics.
zos_2byte_mnemonics = {
   0x1a : { "name" : "AR",
            "func" : RX },
   0x5a : { "name" : "A",
            "func" : RR },
   0xfa : { "name" : "AP",
            "func" : SS_L },
   0x4a : { "name" : "AH",
            "func" : RX },
   0x5e : { "name" : "AL",
            "func" : RX },
   0x1e : { "name" : "ALR",
            "func" : RR },
   0x36 : { "name" : "AXR",
            "func" : RR },
   0x6a : { "name" : "AD",
            "func" : RX },
   0x2a : { "name" : "ADR",
            "func" : RR },
   0x7a : { "name" : "AE",
            "func" : RX },
   0x3a : { "name" : "AER",
            "func" : RR },
   0x6e : { "name" : "AW",
            "func" : RX },
   0x2e : { "name" : "AWR",
            "func" : RR },
   0x7e : { "name" : "AU",
            "func" : RX },
   0x3e : { "name" : "AUR",
            "func" : RR },
   0x54 : { "name" : "N",
            "func" : RX },
   0x14 : { "name" : "NR",
            "func" : RR },
   0xd4 : { "name" : "NC",
            "func" : SS },
   0x94 : { "name" : "NI",
            "func" : SI },
   0x45 : { "name" : "BAL",
            "func" : RX },
   0x05 : { "name" : "BALR",
            "func" : RR },
   0x4d : { "name" : "BAS",
            "func" : RX },
   0x0d : { "name" : "BASR",
            "func" : RR },
   0x0c : { "name" : "BASSM",
            "func" : RR },
   0x0b : { "name" : "BSM",
            "func" : RR },
   0x47 : { "name" : "BC",
            "func" : RX_M },
   0x07 : { "name" : "BCR",
            "func" : RR },
   0x46 : { "name" : "BCT",
            "func" : RX },
   0x06 : { "name" : "BCTR",
            "func" : RR },
   0x86 : { "name" : "BXH",
            "func" : RS },
   0x87 : { "name" : "BXLE",
            "func" : RS },
   0x84 : { "name" : "BRXH",
            "func" : RSI },
   0x85 : { "name" : "BRXLE",
            "func" : RSI },
   0x59 : { "name" : "C",
            "func" : RX },
   0x19 : { "name" : "CR",
            "func" : RR },
   0x69 : { "name" : "CD",
            "func" : RX },
   0x29 : { "name" : "CDR",
            "func" : RR },
   0x79 : { "name" : "CE",
            "func" : RX },
   0x39 : { "name" : "CER",
            "func" : RR },
   0xba : { "name" : "CS",
            "func" : RS },
   0xf9 : { "name" : "CP",
            "func" : SS_L },
   0xbb : { "name" : "CDS",
            "func" : RS },
   0x49 : { "name" : "CH",
            "func" : RX },
   0x55 : { "name" : "CL",
            "func" : RX },
   0x15 : { "name" : "CLR",
            "func" : RR },
   0xd5 : { "name" : "CLC",
            "func" : SS },
   0x95 : { "name" : "CLI",
            "func" : SI },
   0xbd : { "name" : "CLM",
            "func" : RS_M },
   0x0f : { "name" : "CLCL",
            "func" : RR },
   0xa9 : { "name" : "CLCLE",
            "func" : RS },
   0x4f : { "name" : "CVB",
            "func" : RX },
   0x4e : { "name" : "CVD",
            "func" : RX },
   0x83 : { "name" : "X",
            "func" : Dd },
   0x5d : { "name" : "D",
            "func" : RX },
   0x1d : { "name" : "DR",
            "func" : RR },
   0x6d : { "name" : "DD",
            "func" : RX },
   0x2d : { "name" : "DDR",
            "func" : RR },
   0x7d : { "name" : "DE",
            "func" : RX },
   0x3d : { "name" : "DER",
            "func" : RR },
   0xfd : { "name" : "DP",
            "func" : SS_L },
   0xde : { "name" : "ED",
            "func" : SS },
   0xdf : { "name" : "EDMK",
            "func" : SS },
   0x57 : { "name" : "X",
            "func" : RX },
   0x17 : { "name" : "XR",
            "func" : RR },
   0xd7 : { "name" : "XC",
            "func" : SS },
   0x97 : { "name" : "XI",
            "func" : SI },
   0x44 : { "name" : "EX",
            "func" : RX },
   0x24 : { "name" : "HDR",
            "func" : RR },
   0x34 : { "name" : "HER",
            "func" : RR },
   0x43 : { "name" : "IC",
            "func" : RX },
   0xbf : { "name" : "ICM",
            "func" : RS_M },
   0x58 : { "name" : "L",
            "func" : RX },
   0x18 : { "name" : "LR",
            "func" : RR },
   0x68 : { "name" : "LD",
            "func" : RX },
   0x28 : { "name" : "LDR",
            "func" : RR },
   0x78 : { "name" : "LE",
            "func" : RX },
   0x38 : { "name" : "LER",
            "func" : RR },
   0x9a : { "name" : "LAM",
            "func" : RS },
   0x41 : { "name" : "LA",
            "func" : RX },
   0x51 : { "name" : "LAE",
            "func" : RX },
   0x12 : { "name" : "LTR",
            "func" : RR },
   0x22 : { "name" : "LTDR",
            "func" : RR },
   0x32 : { "name" : "LTER",
            "func" : RR },
   0x13 : { "name" : "LCR",
            "func" : RR },
   0x23 : { "name" : "LCDR",
            "func" : RR },
   0x33 : { "name" : "LCER",
            "func" : RR },
   0xb7 : { "name" : "LCTL",
            "func" : RS },
   0x48 : { "name" : "LH",
            "func" : RX },
   0x98 : { "name" : "LM",
            "func" : RS },
   0xef : { "name" : "LMD",
            "func" : SS_R },
   0x11 : { "name" : "LNR",
            "func" : RR },
   0x21 : { "name" : "LNDR",
            "func" : RR },
   0x31 : { "name" : "LNER",
            "func" : RR },
   0x10 : { "name" : "LPR",
            "func" : RR },
   0x20 : { "name" : "LPDR",
            "func" : RR },
   0x30 : { "name" : "LPER",
            "func" : RR },
   0x82 : { "name" : "LPSW",
            "func" : S },
   0xb1 : { "name" : "LRA",
            "func" : RX },
   0x25 : { "name" : "LDXR",
            "func" : RR },
   0x25 : { "name" : "LRDR",
            "func" : RR },
   0x35 : { "name" : "LEDR",
            "func" : RR },
   0x35 : { "name" : "LRER",
            "func" : RR },
   0xaf : { "name" : "MC",
            "func" : SI },
   0xd2 : { "name" : "MVC",
            "func" : SS },
   0x92 : { "name" : "MVI",
            "func" : SI },
   0xe8 : { "name" : "MVCIN",
            "func" : SS },
   0x0e : { "name" : "MVCL",
            "func" : RR },
   0xa8 : { "name" : "MVCLE",
            "func" : RS },
   0xd1 : { "name" : "MVN",
            "func" : SS },
   0xda : { "name" : "MVCP",
            "func" : SS_DD },
   0xdb : { "name" : "MVCS",
            "func" : SS_DD },
   0xd9 : { "name" : "MVCK",
            "func" : SS_DD },
   0xf1 : { "name" : "MVO",
            "func" : SS_L },
   0xd3 : { "name" : "MVZ",
            "func" : SS },
   0x5c : { "name" : "M",
            "func" : RX },
   0x1c : { "name" : "MR",
            "func" : RR },
   0x26 : { "name" : "MXR",
            "func" : RR },
   0x6c : { "name" : "MD",
            "func" : RX },
   0x2c : { "name" : "MDR",
            "func" : RR },
   0x67 : { "name" : "MXD",
            "func" : RX },
   0x27 : { "name" : "MXDR",
            "func" : RR },
   0x7c : { "name" : "MDE",
            "func" : RX },
   0x3c : { "name" : "MDER",
            "func" : RR },
   0x7c : { "name" : "ME",
            "func" : RX },
   0x3c : { "name" : "MER",
            "func" : RR },
   0xfc : { "name" : "MP",
            "func" : SS_L },
   0x4c : { "name" : "MH",
            "func" : RX },
   0x71 : { "name" : "MS",
            "func" : RX },
   0x56 : { "name" : "O",
            "func" : RX },
   0x16 : { "name" : "OR",
            "func" : RR },
   0xd6 : { "name" : "OC",
            "func" : SS },
   0x96 : { "name" : "OI",
            "func" : SI },
   0xf2 : { "name" : "PACK",
            "func" : SS_L },
   0xe9 : { "name" : "PKA",
            "func" : SS_D },
   0xe1 : { "name" : "PKU",
            "func" : SS_D },
   0xee : { "name" : "PLO",
            "func" : SS_RR },
   0x04 : { "name" : "SPM",
            "func" : RR_R },
   0x80 : { "name" : "SSM",
            "func" : S },
   0xf0 : { "name" : "SRP",
            "func" : SS_I },
   0x8f : { "name" : "SLDA",
            "func" : RS_D },
   0x8d : { "name" : "SLDL",
            "func" : RS_D },
   0x8b : { "name" : "SLA",
            "func" : RS_D },
   0x89 : { "name" : "SLL",
            "func" : RS_D },
   0x8e : { "name" : "SRDA",
            "func" : RS_D },
   0x8c : { "name" : "SRDL",
            "func" : RS_D },
   0x8a : { "name" : "SRA",
            "func" : RS_D },
   0x88 : { "name" : "SRL",
            "func" : RS_D },
   0xae : { "name" : "SIGP",
            "func" : RS },
   0x50 : { "name" : "ST",
            "func" : RX },
   0x60 : { "name" : "STD",
            "func" : RX },
   0x70 : { "name" : "STE",
            "func" : RX },
   0x9b : { "name" : "STAM",
            "func" : RS },
   0x42 : { "name" : "STC",
            "func" : RX },
   0xbe : { "name" : "STCM",
            "func" : RS_M },
   0xb6 : { "name" : "STCTL",
            "func" : RS },
   0x40 : { "name" : "STH",
            "func" : RX },
   0x90 : { "name" : "STM",
            "func" : RS },
   0xac : { "name" : "STNSM",
            "func" : SI },
   0xad : { "name" : "STOSM",
            "func" : SI },
   0x5b : { "name" : "S",
            "func" : RX },
   0x1b : { "name" : "SR",
            "func" : RR },
   0xfb : { "name" : "SP",
            "func" : SS_L },
   0x4b : { "name" : "SH",
            "func" : RX },
   0x5f : { "name" : "SL",
            "func" : RX },
   0x1f : { "name" : "SLR",
            "func" : RR },
   0x37 : { "name" : "SXR",
            "func" : RR },
   0x6b : { "name" : "SD",
            "func" : RX },
   0x2b : { "name" : "SDR",
            "func" : RR },
   0x7b : { "name" : "SE",
            "func" : RX },
   0x3b : { "name" : "SER",
            "func" : RR },
   0x6f : { "name" : "SW",
            "func" : RX },
   0x2f : { "name" : "SWR",
            "func" : RR },
   0x7f : { "name" : "SU",
            "func" : RX },
   0x3f : { "name" : "SUR",
            "func" : RR },
   0x0a : { "name" : "SVC",
            "func" : I },
   0x93 : { "name" : "TS",
            "func" : S },
   0x91 : { "name" : "TM",
            "func" : SI },
   0x99 : { "name" : "TRACE",
            "func" : RS },
   0xdc : { "name" : "TR",
            "func" : SS },
   0xdd : { "name" : "TRT",
            "func" : SS },
   0xd0 : { "name" : "TRTR",
            "func" : SS },
   0xf3 : { "name" : "UNPK",
            "func" : SS_L },
   0xea : { "name" : "UNPKA",
            "func" : SS },
   0xe2 : { "name" : "UNPKU",
            "func" : SS },
   0xf8 : { "name" : "ZAP",
            "func" : SS_L }
}

# @def   zos_3byte_mnomics
# @brief A dictionary of zOS 3 byte Mnemonics.
zos_3byte_mnemonics = {
   0xa7a : { "name" : "AHI",
             "func" : RI },
   0xa7b : { "name" : "AGHI",
             "func" : RI },
   0xc29 : { "name" : "AFI",
             "func" : RIL },
   0xc28 : { "name" : "AGFI",
             "func" : RIL },
   0xc2b : { "name" : "ALFI",
             "func" : RIL },
   0xc2a : { "name" : "ALGFI",
             "func" : RIL },
   0xa54 : { "name" : "NIHH",
             "func" : RI },
   0xa55 : { "name" : "NIHL",
             "func" : RI },
   0xc0a : { "name" : "NIHF",
             "func" : RIL },
   0xa56 : { "name" : "NILH",
             "func" : RI },
   0xa57 : { "name" : "NILL",
             "func" : RI },
   0xc0b : { "name" : "NILF",
             "func" : RIL },
   0xa75 : { "name" : "BRAS",
             "func" : RI },
   0xc05 : { "name" : "BRASL",
             "func" : RIL },
   0xa74 : { "name" : "BRC",
             "func" : RI_M },
   0xc04 : { "name" : "BRCL",
             "func" : RIL_M },
   0xa76 : { "name" : "BRCT",
             "func" : RI },
   0xa77 : { "name" : "BRCTG",
             "func" : RI },
   0xc82 : { "name" : "CSST",
             "func" : SSF },
   0xa7e : { "name" : "CHI",
             "func" : RI },
   0xa7f : { "name" : "CGHI",
             "func" : RI },
   0xc65 : { "name" : "CHRL",
             "func" : RIL },
   0xc64 : { "name" : "CGHRL",
             "func" : RIL },
   0xc2d : { "name" : "CFI",
             "func" : RIL },
   0xc2c : { "name" : "CGFI",
             "func" : RIL },
   0xc2f : { "name" : "CLFI",
             "func" : RIL },
   0xc2e : { "name" : "CLGFI",
             "func" : RIL },
   0xc6f : { "name" : "CLRL",
             "func" : RIL },
   0xc67 : { "name" : "CLHRL",
             "func" : RIL },
   0xc6a : { "name" : "CLGRL",
             "func" : RIL },
   0xc66 : { "name" : "CLGHRL",
             "func" : RIL },
   0xc6e : { "name" : "CLGFRL",
             "func" : RIL },
   0xc6d : { "name" : "CRL",
             "func" : RIL },
   0xc68 : { "name" : "CGRL",
             "func" : RIL },
   0xc6c : { "name" : "CGFRL",
             "func" : RIL },
   0xc06 : { "name" : "XIHF",
             "func" : RIL },
   0xc07 : { "name" : "XILR",
             "func" : RIL },
   0xc60 : { "name" : "EXRL",
             "func" : RIL },
   0xc81 : { "name" : "ECTG",
             "func" : SSF },
   0xa50 : { "name" : "IIHH",
             "func" : RI },
   0xa51 : { "name" : "IIHL",
             "func" : RI },
   0xc08 : { "name" : "IIHF",
             "func" : RIL },
   0xa52 : { "name" : "IILH",
             "func" : RI },
   0xa53 : { "name" : "IILL",
             "func" : RI },
   0xc09 : { "name" : "IILF",
             "func" : RIL },
   0xc00 : { "name" : "LARL",
             "func" : RIL },
   0xa78 : { "name" : "LHI",
             "func" : RI },
   0xa79 : { "name" : "LGHI",
             "func" : RI },
   0xc45 : { "name" : "LHRL",
             "func" : RIL },
   0xc44 : { "name" : "LGHRL",
             "func" : RIL },
   0xc01 : { "name" : "LGFI",
             "func" : RIL },
   0xc42 : { "name" : "LLHRL",
             "func" : RIL },
   0xc46 : { "name" : "LLGHRL",
             "func" : RIL },
   0xa5c : { "name" : "LLIHH",
             "func" : RI },
   0xa5d : { "name" : "LLIHL",
             "func" : RI },
   0xc0e : { "name" : "LLIHF",
             "func" : RIL },
   0xa5e : { "name" : "LLILH",
             "func" : RI },
   0xa5f : { "name" : "LLILL",
             "func" : RI },
   0xc0f : { "name" : "LLILF",
             "func" : RIL },
   0xc4e : { "name" : "LLGFRL",
             "func" : RIL },
   0xc4d : { "name" : "LRL",
             "func" : RIL },
   0xc48 : { "name" : "LGRL",
             "func" : RIL },
   0xc4c : { "name" : "LGFRL",
             "func" : RIL },
   0xc80 : { "name" : "MVCOS",
             "func" : SSF },
   0xa7c : { "name" : "MHI",
             "func" : RI },
   0xa7d : { "name" : "MGHI",
             "func" : RI },
   0xc21 : { "name" : "MSFI",
             "func" : RIL },
   0xc20 : { "name" : "MSGFI",
             "func" : RIL },
   0xa58 : { "name" : "OIHH",
             "func" : RI },
   0xa59 : { "name" : "OIHL",
             "func" : RI },
   0xc0c : { "name" : "OIHF",
             "func" : RIL },
   0xa5a : { "name" : "OILH",
             "func" : RI },
   0xa5b : { "name" : "OILL",
             "func" : RI },
   0xc0d : { "name" : "OILF",
             "func" : RIL },
   0xc62 : { "name" : "PFDRL",
             "func" : RIL_M },
   0xc47 : { "name" : "STHRL",
             "func" : RIL },
   0xc4f : { "name" : "STRL",
             "func" : RIL },
   0xc4b : { "name" : "STGRL",
             "func" : RIL },
   0xc25 : { "name" : "SLFI",
             "func" : RIL },
   0xa72 : { "name" : "TMHH",
             "func" : RI },
   0xa73 : { "name" : "TMHL",
             "func" : RI },
   0xa70 : { "name" : "TMLH",
             "func" : RI },
   0xa71 : { "name" : "TMLL",
             "func" : RI },
   0xa70 : { "name" : "TMH",
             "func" : RI },
   0xa71 : { "name" : "TML",
             "func" : RI },
   0xc24 : { "name" : "SLGFI",
             "func" : RIL }
}

# @def   zos_4byte_mnomics
# @brief A dictionary of zOS 4 byte Mnemonics.
zos_4byte_mnemonics = {
   0xe35a : { "name" : "AY",
              "func" : RXY },
   0xe308 : { "name" : "AG",
              "func" : RXY },
   0xb908 : { "name" : "AGR",
              "func" : RRE },
   0xe318 : { "name" : "AGF",
              "func" : RXY },
   0xb918 : { "name" : "AGFR",
              "func" : RRE },
   0xb34a : { "name" : "AXBR",
              "func" : RRE },
   0xb3da : { "name" : "AXTR",
              "func" : RRR },
   0xed1a : { "name" : "ADB",
              "func" : RXE },
   0xb31a : { "name" : "ADBR",
              "func" : RRE },
   0xb3d2 : { "name" : "ADTR",
              "func" : RRR },
   0xed0a : { "name" : "AEB",
              "func" : RXE },
   0xb30a : { "name" : "AEBR",
              "func" : RRE },
   0xe37a : { "name" : "AHY",
              "func" : RXY },
   0xeb6a : { "name" : "ASI",
              "func" : SIY },
   0xeb7a : { "name" : "AGSI",
              "func" : SIY },
   0xe35e : { "name" : "ALY",
              "func" : RXY },
   0xe30a : { "name" : "ALG",
              "func" : RXY },
   0xb90a : { "name" : "ALGR",
              "func" : RRE },
   0xe31a : { "name" : "ALGF",
              "func" : RXY },
   0xb91a : { "name" : "ALGFR",
              "func" : RRE },
   0xe398 : { "name" : "ALC",
              "func" : RXY },
   0xb998 : { "name" : "ALCR",
              "func" : RRE },
   0xe388 : { "name" : "ALCG",
              "func" : RXY },
   0xb988 : { "name" : "ALCGR",
              "func" : RRE },
   0xeb6e : { "name" : "ALSI",
              "func" : SIY },
   0xeb7e : { "name" : "ALGSI",
              "func" : SIY },
   0xe354 : { "name" : "NY",
              "func" : RXY },
   0xe380 : { "name" : "NG",
              "func" : RXY },
   0xb980 : { "name" : "NGR",
              "func" : RRE },
   0xeb54 : { "name" : "NIY",
              "func" : SIY },
   0xb25a : { "name" : "BSA",
              "func" : RRE },
   0xb240 : { "name" : "BAKR",
              "func" : RRE },
   0xb258 : { "name" : "BSG",
              "func" : RRE },
   0xe346 : { "name" : "BCTG",
              "func" : RXY },
   0xb946 : { "name" : "BCTGR",
              "func" : RRE },
   0xeb44 : { "name" : "BXHG",
              "func" : RSY },
   0xeb45 : { "name" : "BXLEG",
              "func" : RSY },
   0xec44 : { "name" : "BRXJG",
              "func" : RIE },
   0xec45 : { "name" : "BRXLG",
              "func" : RIE },
   0xb276 : { "name" : "XSCH",
              "func" : S_I },
   0xb241 : { "name" : "CKSM",
              "func" : RRE },
   0xb92e : { "name" : "KM",
              "func" : RRE },
   0xb92f : { "name" : "KMC",
              "func" : RRE },
   0xb230 : { "name" : "CSCH",
              "func" : S_I },
   0xe359 : { "name" : "CY",
              "func" : RXY },
   0xe320 : { "name" : "CG",
              "func" : RXY },
   0xb920 : { "name" : "CGR",
              "func" : RRE },
   0xe330 : { "name" : "CGF",
              "func" : RXY },
   0xb930 : { "name" : "CGFR",
              "func" : RRE },
   0xb349 : { "name" : "CXBR",
              "func" : RRE },
   0xb3ec : { "name" : "CXTR",
              "func" : RRE },
   0xb369 : { "name" : "CXR",
              "func" : RRE },
   0xed19 : { "name" : "CDB",
              "func" : RXE },
   0xb319 : { "name" : "CDBR",
              "func" : RRE },
   0xb3e4 : { "name" : "CDTR",
              "func" : RRE },
   0xed09 : { "name" : "CEB",
              "func" : RXE },
   0xb309 : { "name" : "CEBR",
              "func" : RRE },
   0xecf6 : { "name" : "CRB",
              "func" : RRS },
   0xece4 : { "name" : "CGRB",
              "func" : RRS },
   0xec76 : { "name" : "CRJ",
              "func" : RIE_M },
   0xec64 : { "name" : "CGRJ",
              "func" : RIE_M },
   0xb21a : { "name" : "CFC",
              "func" : S },
   0xb348 : { "name" : "KXBR",
              "func" : RRE },
   0xb3e8 : { "name" : "KXTR",
              "func" : RRE },
   0xed18 : { "name" : "KDB",
              "func" : RXE },
   0xb318 : { "name" : "KDBR",
              "func" : RRE },
   0xb3e0 : { "name" : "KDTR",
              "func" : RRE },
   0xed08 : { "name" : "KEB",
              "func" : RXE },
   0xb308 : { "name" : "KEBR",
              "func" : RRE },
   0xeb14 : { "name" : "CSY",
              "func" : RSY },
   0xeb30 : { "name" : "CSG",
              "func" : RSY },
   0xb250 : { "name" : "CSP",
              "func" : RRE },
   0xb98a : { "name" : "CSPG",
              "func" : RRE },
   0xb972 : { "name" : "CRT",
              "func" : RRF_M },
   0xb960 : { "name" : "CGRT",
              "func" : RRF_M },
   0xb3fc : { "name" : "CEXTR",
              "func" : RRE },
   0xb3f4 : { "name" : "CEDTR",
              "func" : RRE },
   0xeb31 : { "name" : "CDSY",
              "func" : RSY },
   0xeb3e : { "name" : "CDSG",
              "func" : RSY },
   0xe379 : { "name" : "CHY",
              "func" : RXY },
   0xe334 : { "name" : "CGH",
              "func" : RXY },
   0xe554 : { "name" : "CHHSI",
              "func" : SIL },
   0xe55c : { "name" : "CHSI",
              "func" : SIL },
   0xe558 : { "name" : "CGHSI",
              "func" : SIL },
   0xecfe : { "name" : "cib" ,
              "func" : RIS },
   0xecfc : { "name" : "CGIB",
              "func" : RIS },
   0xec7e : { "name" : "CIJ",
              "func" : RIE },
   0xec7c : { "name" : "CGIJ",
              "func" : RIE },
   0xec72 : { "name" : "CIT",
              "func" : RIE_IM },
   0xec70 : { "name" : "CGIT",
              "func" : RIE_IM },
   0xe355 : { "name" : "CLY",
              "func" : RXY },
   0xe321 : { "name" : "CLG",
              "func" : RXY },
   0xb921 : { "name" : "CLGR",
              "func" : RRE },
   0xe331 : { "name" : "CLGF",
              "func" : RXY },
   0xb931 : { "name" : "CLGFR",
              "func" : RRE },
   0xeb55 : { "name" : "CLIY",
              "func" : SIY },
   0xecf7 : { "name" : "CLRB",
              "func" : RRS },
   0xece5 : { "name" : "CLGRB",
              "func" : RRS },
   0xec77 : { "name" : "CLRJ",
              "func" : RIE_M },
   0xec65 : { "name" : "CLGRJ",
              "func" : RIE_M },
   0xb973 : { "name" : "CLRT",
              "func" : RRF_M },
   0xb961 : { "name" : "CLGRT",
              "func" : RRF_M },
   0xeb20 : { "name" : "CLMH",
              "func" : RSY_M },
   0xeb21 : { "name" : "CLMY",
              "func" : RSY_M },
   0xe555 : { "name" : "CLHHSI",
              "func" : SIL },
   0xe55d : { "name" : "CLFHSI",
              "func" : SIL },
   0xe559 : { "name" : "CLGHSI",
              "func" : SIL },
   0xecff : { "name" : "CLIB",
              "func" : RIS },
   0xecfd : { "name" : "CLGIB",
              "func" : RIS },
   0xec7f : { "name" : "CLIJ",
              "func" : RIE_MI },
   0xec7d : { "name" : "CLGIJ",
              "func" : RIE_MI },
   0xec73 : { "name" : "CLFIT",
              "func" : RIE_IM },
   0xec71 : { "name" : "CLGIT",
              "func" : RIE_IM },
   0xeb8f : { "name" : "CLCLU",
              "func" : RSY },
   0xb25d : { "name" : "CLST",
              "func" : RRE },
   0xb257 : { "name" : "CUSE",
              "func" : RRE },
   0xb263 : { "name" : "CMPSC",
              "func" : RRE },
   0xb93e : { "name" : "KIMD",
              "func" : RRE },
   0xb93f : { "name" : "KLMD",
              "func" : RRE },
   0xb91e : { "name" : "KMAC",
              "func" : RRE },
   0xb359 : { "name" : "THDR",
              "func" : RRE },
   0xb358 : { "name" : "THDER",
              "func" : RRE },
   0xb396 : { "name" : "CXFBR",
              "func" : RRE },
   0xb3b6 : { "name" : "CXFR",
              "func" : RRE },
   0xb395 : { "name" : "CDFBR",
              "func" : RRE },
   0xb3b5 : { "name" : "CDFR",
              "func" : RRE },
   0xb394 : { "name" : "CEFBR",
              "func" : RRE },
   0xb3b4 : { "name" : "CEFR",
              "func" : RRE },
   0xb3a6 : { "name" : "CXGBR",
              "func" : RRE },
   0xb3f9 : { "name" : "CXGTR",
              "func" : RRE },
   0xb3c6 : { "name" : "CXGR",
              "func" : RRE },
   0xb3a5 : { "name" : "CDGBR",
              "func" : RRE },
   0xb3f1 : { "name" : "CDGTR",
              "func" : RRE },
   0xb3c5 : { "name" : "CDGR",
              "func" : RRE },
   0xb3a4 : { "name" : "CEGBR",
              "func" : RRE },
   0xb3c4 : { "name" : "CDGR",
              "func" : RRE },
   0xb3fb : { "name" : "CXSTR",
              "func" : RRE },
   0xb3f3 : { "name" : "CDSTR",
              "func" : RRE },
   0xb3fa : { "name" : "CXUTR",
              "func" : RRE },
   0xb3f2 : { "name" : "CDUTR",
              "func" : RRE },
   0xb350 : { "name" : "TBEDR",
              "func" : RRF },
   0xb351 : { "name" : "TBDR",
              "func" : RRF },
   0xe306 : { "name" : "CVBY",
              "func" : RXY },
   0xe30e : { "name" : "CVBG",
              "func" : RXY },
   0xe326 : { "name" : "CVDY",
              "func" : RXY },
   0xe32e : { "name" : "CVDG",
              "func" : RXY },
   0xb39a : { "name" : "CFXBR",
              "func" : RRF },
   0xb3aa : { "name" : "CGXBR",
              "func" : RRF },
   0xb3e9 : { "name" : "CGXTR",
              "func" : RRF },
   0xb3ba : { "name" : "CFXR",
              "func" : RRF },
   0xb3ca : { "name" : "CGXR",
              "func" : RRF },
   0xb399 : { "name" : "CFDBR",
              "func" : RRF },
   0xb3a9 : { "name" : "CGDBR",
              "func" : RRF },
   0xb3e1 : { "name" : "CGDTR",
              "func" : RRF },
   0xb3b9 : { "name" : "CFDR",
              "func" : RRF },
   0xb3c9 : { "name" : "CGDR",
              "func" : RRF },
   0xb398 : { "name" : "CFEBR",
              "func" : RRF },
   0xb3a8 : { "name" : "CGEBR",
              "func" : RRF },
   0xb3b8 : { "name" : "CFER",
              "func" : RRF },
   0xb3c8 : { "name" : "CGER",
              "func" : RRF },
   0xb3eb : { "name" : "CSXTR",
              "func" : RRF_M },
   0xb3e3 : { "name" : "CSDTR",
              "func" : RRF_M },
   0xb3ea : { "name" : "CUXTR",
              "func" : RRE },
   0xb3e2 : { "name" : "CUDTR",
              "func" : RRE },
   0xb2a6 : { "name" : "CUUTF",
              "func" : RRF_RRM },
   0xb9b1 : { "name" : "CU24",
              "func" : RRF_RRM },
   0xb2a6 : { "name" : "CU21",
              "func" : RRF_RRM },
   0xb9b3 : { "name" : "CU42",
              "func" : RRE },
   0xb9b2 : { "name" : "CU41",
              "func" : RRE },
   0xb2a7 : { "name" : "CUTFU",
              "func" : RRF_RRM },
   0xb2a7 : { "name" : "CU12",
              "func" : RRF_RRM },
   0xb9b0 : { "name" : "CU14",
              "func" : RRF_RRM },
   0xb24d : { "name" : "CPYA",
              "func" : RRE },
   0xb372 : { "name" : "CPSDR",
              "func" : RRF_R },
   0xb34d : { "name" : "DXBR",
              "func" : RRE },
   0xb3d9 : { "name" : "DXTR",
              "func" : RRR },
   0xb22d : { "name" : "DXR",
              "func" : RRE },
   0xed1d : { "name" : "DDB",
              "func" : RXE },
   0xb31d : { "name" : "DDBR",
              "func" : RRE },
   0xb3d1 : { "name" : "DDTR",
              "func" : RRR },
   0xed0d : { "name" : "DEB",
              "func" : RXE },
   0xb30d : { "name" : "DEBR",
              "func" : RRE },
   0xe397 : { "name" : "DL",
              "func" : RXY },
   0xb997 : { "name" : "DLR",
              "func" : RRE },
   0xe387 : { "name" : "DLG",
              "func" : RXY },
   0xb987 : { "name" : "DLGR",
              "func" : RRE },
   0xe30d : { "name" : "DSG",
              "func" : RXY },
   0xb90d : { "name" : "DSGR",
              "func" : RRE },
   0xe31d : { "name" : "DSGF",
              "func" : RXY },
   0xb91d : { "name" : "DSGFR",
              "func" : RRE },
   0xb35b : { "name" : "DIDBR",
              "func" : RRF_RM },
   0xb353 : { "name" : "DIEBR",
              "func" : RRF_RM },
   0xe357 : { "name" : "XY",
              "func" : RXY },
   0xe382 : { "name" : "XG",
              "func" : RXY },
   0xb982 : { "name" : "XGR",
              "func" : RRE },
   0xeb57 : { "name" : "XIY",
              "func" : SIY },
   0xb24f : { "name" : "EAR",
              "func" : RRE },
   0xb99d : { "name" : "ESEA",
              "func" : RRE_R },
   0xb3ed : { "name" : "EEXTR",
              "func" : RRE },
   0xb3e5 : { "name" : "EEDTR",
              "func" : RRE },
   0xeb4c : { "name" : "ECAG",
              "func" : RSY },
   0xb38c : { "name" : "EFPC",
              "func" : RRE_R },
   0xb226 : { "name" : "EPAR",
              "func" : RRE_R },
   0xb99a : { "name" : "EPAIR",
              "func" : RRE_R },
   0xb98d : { "name" : "EPSW",
              "func" : RRE },
   0xb227 : { "name" : "ESAR",
              "func" : RRE_R },
   0xb99b : { "name" : "ESAIR",
              "func" : RRE_R },
   0xb3ef : { "name" : "ESXTR",
              "func" : RRE },
   0xb3e7 : { "name" : "ESDTR",
              "func" : RRE },
   0xb249 : { "name" : "EREG",
              "func" : RRE },
   0xb90e : { "name" : "EREGG",
              "func" : RRE },
   0xb24a : { "name" : "ESTA",
              "func" : RRE },
   0xb983 : { "name" : "FLOGR",
              "func" : RRE },
   0xb231 : { "name" : "HSCH",
              "func" : S_I },
   0xb224 : { "name" : "IAC",
              "func" : RRE_R },
   0xb3fe : { "name" : "IEXTR",
              "func" : RRF_R },
   0xe373 : { "name" : "ICY",
              "func" : RXY },
   0xeb80 : { "name" : "ICMH",
              "func" : RSY_M },
   0xeb81 : { "name" : "ICMY",
              "func" : RSY_M },
   0xb222 : { "name" : "IPM",
              "func" : RRE_R },
   0xb20b : { "name" : "IPK",
              "func" : S_I },
   0xb229 : { "name" : "ISKE",
              "func" : RRE },
   0xb223 : { "name" : "IVSK",
              "func" : RRE },
   0xb98e : { "name" : "IDTE",
              "func" : RRF_R },
   0xb221 : { "name" : "IPTE",
              "func" : RRE },
   0xe358 : { "name" : "LY",
              "func" : RXY },
   0xe304 : { "name" : "LG",
              "func" : RXY },
   0xb904 : { "name" : "LGR",
              "func" : RRE },
   0xe314 : { "name" : "LGF",
              "func" : RXY },
   0xb914 : { "name" : "LGFR",
              "func" : RRE },
   0xb365 : { "name" : "LXR",
              "func" : RRE },
   0xed65 : { "name" : "LDY",
              "func" : RXY },
   0xed64 : { "name" : "LEY",
              "func" : RXY },
   0xeb9a : { "name" : "LAMY",
              "func" : RSY },
   0xe371 : { "name" : "LAY",
              "func" : RXY },
   0xe375 : { "name" : "LAEY",
              "func" : RXY },
   0xe500 : { "name" : "LASP",
              "func" : SSE },
   0xe312 : { "name" : "LT",
              "func" : RXY },
   0xe302 : { "name" : "LTG",
              "func" : RXY },
   0xb902 : { "name" : "LTGR",
              "func" : RRE },
   0xe332 : { "name" : "LTGF",
              "func" : RXY },
   0xb912 : { "name" : "LTGFR",
              "func" : RRE },
   0xb342 : { "name" : "LTXBR",
              "func" : RRE },
   0xb3de : { "name" : "LTXTR",
              "func" : RRE },
   0xb362 : { "name" : "LTXR",
              "func" : RRE },
   0xb312 : { "name" : "LTDBR",
              "func" : RRE },
   0xb302 : { "name" : "LTEBR",
              "func" : RRE },
   0xe376 : { "name" : "LB",
              "func" : RXY },
   0xb926 : { "name" : "LBR",
              "func" : RRE },
   0xe377 : { "name" : "LGB",
              "func" : RXY },
   0xb906 : { "name" : "LGBR",
              "func" : RRE },
   0xb903 : { "name" : "LCGR",
              "func" : RRE },
   0xb913 : { "name" : "LCGFR",
              "func" : RRE },
   0xb343 : { "name" : "LCXBR",
              "func" : RRE },
   0xb363 : { "name" : "LCXR",
              "func" : RRE },
   0xb313 : { "name" : "LCDBR",
              "func" : RRE },
   0xb373 : { "name" : "LCDFR",
              "func" : RRE },
   0xb303 : { "name" : "LCEBR",
              "func" : RRE },
   0xeb2f : { "name" : "LCTLG",
              "func" : RSY },
   0xb347 : { "name" : "FIXBR",
              "func" : RRF },
   0xb3df : { "name" : "FIXTR",
              "func" : RRF_RMRM },
   0xb367 : { "name" : "FIXR",
              "func" : RRE },
   0xb35f : { "name" : "FIDBR",
              "func" : RRF },
   0xb3d7 : { "name" : "FIDTR",
              "func" : RRF_RMRM },
   0xb37f : { "name" : "FIDR",
              "func" : RRE },
   0xb357 : { "name" : "FIEBR",
              "func" : RRF },
   0xb377 : { "name" : "FIER",
              "func" : RRE },
   0xb29d : { "name" : "LFPC",
              "func" : S },
   0xb2bd : { "name" : "LFAS",
              "func" : S },
   0xb3c1 : { "name" : "LDGR",
              "func" : RRE },
   0xb3cd : { "name" : "LGDR",
              "func" : RRE },
   0xb927 : { "name" : "LHR",
              "func" : RRE },
   0xe378 : { "name" : "LHY",
              "func" : RXY },
   0xe315 : { "name" : "LGH",
              "func" : RXY },
   0xb907 : { "name" : "LGHR",
              "func" : RRE },
   0xed05 : { "name" : "LXDB",
              "func" : RXE },
   0xb305 : { "name" : "LXDBR",
              "func" : RRE },
   0xb3dc : { "name" : "LXDTR",
              "func" : RRF_M },
   0xed25 : { "name" : "LXD",
              "func" : RXE },
   0xb325 : { "name" : "LXDR",
              "func" : RRE },
   0xed06 : { "name" : "LXEB",
              "func" : RXE },
   0xb306 : { "name" : "LXEBR",
              "func" : RRE },
   0xed26 : { "name" : "LXE",
              "func" : RXE },
   0xb326 : { "name" : "LXER",
              "func" : RRE },
   0xed04 : { "name" : "LDEB",
              "func" : RXE },
   0xb304 : { "name" : "LDEBR",
              "func" : RRE },
   0xb3d4 : { "name" : "LDETR",
              "func" : RRF_M },
   0xed24 : { "name" : "LDE",
              "func" : RXE },
   0xb324 : { "name" : "LDER",
              "func" : RRE },
   0xe316 : { "name" : "LLGF",
              "func" : RXY },
   0xb916 : { "name" : "LLGFR",
              "func" : RRE },
   0xe394 : { "name" : "LLC",
              "func" : RXY },
   0xb994 : { "name" : "LLCR",
              "func" : RRE },
   0xe390 : { "name" : "LLGC",
              "func" : RXY },
   0xb984 : { "name" : "LLGCR",
              "func" : RRE },
   0xe395 : { "name" : "LLH",
              "func" : RXY },
   0xb995 : { "name" : "LLHR",
              "func" : RRE },
   0xe391 : { "name" : "LLGH",
              "func" : RXY },
   0xb985 : { "name" : "LLGHR",
              "func" : RRE },
   0xe317 : { "name" : "LLGT",
              "func" : RXY },
   0xb917 : { "name" : "LLGTR",
              "func" : RRE },
   0xeb98 : { "name" : "LMY",
              "func" : RSY },
   0xeb04 : { "name" : "LMG",
              "func" : RSY },
   0xeb96 : { "name" : "LMH",
              "func" : RSY },
   0xb901 : { "name" : "LNGR",
              "func" : RRE },
   0xb911 : { "name" : "LNGFR",
              "func" : RRE },
   0xb341 : { "name" : "LNXBR",
              "func" : RRE },
   0xb361 : { "name" : "LNXR",
              "func" : RRE },
   0xb311 : { "name" : "LNDBR",
              "func" : RRE },
   0xb371 : { "name" : "LNDFR",
              "func" : RRE },
   0xb301 : { "name" : "LNEBR",
              "func" : RRE },
   0xb9aa : { "name" : "LPTEA",
              "func" : RRF_RM },
   0xe38f : { "name" : "LPQ",
              "func" : RXY },
   0xb900 : { "name" : "LPGR",
              "func" : RRE },
   0xb910 : { "name" : "LPGFR",
              "func" : RRE },
   0xb340 : { "name" : "LPXBR",
              "func" : RRE },
   0xb360 : { "name" : "LPXR",
              "func" : RRE },
   0xb310 : { "name" : "LPDBR",
              "func" : RRE },
   0xb370 : { "name" : "LPDFR",
              "func" : RRE },
   0xb300 : { "name" : "LPEBR",
              "func" : RRE },
   0xb2b2 : { "name" : "LPSWE",
              "func" : S },
   0xe313 : { "name" : "LRAY",
              "func" : RXY },
   0xe303 : { "name" : "LRAG",
              "func" : RXY },
   0xe31f : { "name" : "LRVH",
              "func" : RXY },
   0xe31e : { "name" : "LRV",
              "func" : RXY },
   0xb91f : { "name" : "LRVR",
              "func" : RRE },
   0xe30f : { "name" : "LRVG",
              "func" : RXY },
   0xb90f : { "name" : "LRVGR",
              "func" : RRE },
   0xb345 : { "name" : "LDXBR",
              "func" : RRE },
   0xb3dd : { "name" : "LDXTR",
              "func" : RRF_RMRM },
   0xb346 : { "name" : "LEXBR",
              "func" : RRE },
   0xb366 : { "name" : "LEXR",
              "func" : RRE },
   0xb344 : { "name" : "LEDBR",
              "func" : RRE },
   0xb3d5 : { "name" : "LEDTR",
              "func" : RRF_RMRM },
   0xb24b : { "name" : "LURA",
              "func" : RRE },
   0xb905 : { "name" : "LURAG",
              "func" : RRE },
   0xb376 : { "name" : "LZXR",
              "func" : RRE_R },
   0xb375 : { "name" : "LZDR",
              "func" : RRE_R },
   0xb374 : { "name" : "LZER",
              "func" : RRE_R },
   0xb247 : { "name" : "MSTA",
              "func" : RRE_R },
   0xb232 : { "name" : "MSCH",
              "func" : S },
   0xe544 : { "name" : "MVHHI",
              "func" : SIL },
   0xe54c : { "name" : "MVHI",
              "func" : SIL },
   0xe548 : { "name" : "MVGHI",
              "func" : SIL },
   0xeb52 : { "name" : "MVIY",
              "func" : SIY },
   0xeb8e : { "name" : "MVCLU",
              "func" : RSY },
   0xb254 : { "name" : "MVPG",
              "func" : RRE },
   0xb255 : { "name" : "MVST",
              "func" : RRE },
   0xe50f : { "name" : "MVCDK",
              "func" : SSE },
   0xe50e : { "name" : "MVCSK",
              "func" : SSE },
   0xed3a : { "name" : "MAY",
              "func" : RXF },
   0xb33a : { "name" : "MAYR",
              "func" : RRF_R },
   0xe35c : { "name" : "MFY",
              "func" : RXY },
   0xb34c : { "name" : "MXBR",
              "func" : RRE },
   0xb3d8 : { "name" : "MXTR",
              "func" : RRR },
   0xed1c : { "name" : "MDB",
              "func" : RXE },
   0xb31c : { "name" : "MDBR",
              "func" : RRE },
   0xb3d0 : { "name" : "MDTR",
              "func" : RRR },
   0xed07 : { "name" : "MXDB",
              "func" : RXE },
   0xb307 : { "name" : "MXDBR",
              "func" : RRE },
   0xed17 : { "name" : "MEEB",
              "func" : RXE },
   0xb317 : { "name" : "MEEBR",
              "func" : RRE },
   0xed37 : { "name" : "MEE",
              "func" : RXE },
   0xb337 : { "name" : "MEER",
              "func" : RRE },
   0xed0c : { "name" : "MDEB",
              "func" : RXE },
   0xb30c : { "name" : "MDEBR",
              "func" : RRE },
   0xed1e : { "name" : "MADB",
              "func" : RXF },
   0xb31e : { "name" : "MADBR",
              "func" : RRF_R },
   0xed3e : { "name" : "MAD",
              "func" : RXF },
   0xb33e : { "name" : "MADR",
              "func" : RRF_R },
   0xed0e : { "name" : "MAEB",
              "func" : RXF },
   0xb30e : { "name" : "MAEBR",
              "func" : RRF_R },
   0xed2e : { "name" : "MAE",
              "func" : RXF },
   0xb32e : { "name" : "MAER",
              "func" : RRF_R },
   0xed3c : { "name" : "MAYH",
              "func" : RXF },
   0xb33c : { "name" : "MAYHR",
              "func" : RRF_R },
   0xed38 : { "name" : "MAYL",
              "func" : RXF },
   0xb338 : { "name" : "MAYLR",
              "func" : RRF_R },
   0xed1f : { "name" : "MSDB",
              "func" : RXF },
   0xb31f : { "name" : "MSDBR",
              "func" : RRF_R },
   0xed3f : { "name" : "MSD",
              "func" : RXF },
   0xb33f : { "name" : "MSDR",
              "func" : RRF_R },
   0xed0f : { "name" : "MSEB",
              "func" : RXF },
   0xb30f : { "name" : "MSEBR",
              "func" : RRF_R },
   0xed2f : { "name" : "MSE",
              "func" : RXF },
   0xb32f : { "name" : "MSER",
              "func" : RRF_R },
   0xe37c : { "name" : "MHY",
              "func" : RXY },
   0xe386 : { "name" : "MLG",
              "func" : RXY },
   0xb986 : { "name" : "MLGR",
              "func" : RRE },
   0xe396 : { "name" : "ML",
              "func" : RXY },
   0xb996 : { "name" : "MLR",
              "func" : RRE },
   0xb252 : { "name" : "MSR",
              "func" : RRE },
   0xe351 : { "name" : "MSY",
              "func" : RXY },
   0xe30c : { "name" : "MSG",
              "func" : RXY },
   0xb90c : { "name" : "MSGR",
              "func" : RRE },
   0xe31c : { "name" : "MSGF",
              "func" : RXY },
   0xb91c : { "name" : "MSGFR",
              "func" : RRE },
   0xed3d : { "name" : "MYH",
              "func" : RXF },
   0xb33d : { "name" : "MYHR",
              "func" : RRF_R },
   0xed39 : { "name" : "MYL",
              "func" : RXF },
   0xb339 : { "name" : "MYLR",
              "func" : RRF_R },
   0xed3b : { "name" : "MY",
              "func" : RXF },
   0xb33b : { "name" : "MYR",
              "func" : RRF_R },
   0xe356 : { "name" : "OY",
              "func" : RXY },
   0xe381 : { "name" : "OG",
              "func" : RXY },
   0xb981 : { "name" : "OGR",
              "func" : RRE },
   0xeb56 : { "name" : "OIY",
              "func" : SIY },
   0xb22e : { "name" : "PGIN",
              "func" : RRE },
   0xb22f : { "name" : "PGOUT",
              "func" : RRE },
   0x010a : { "name" : "PFPO",
              "func" : E },
   0xb9af : { "name" : "PFMF",
              "func" : RRE },
   0x0104 : { "name" : "PTFF",
              "func" : E },
   0xb9a2 : { "name" : "PTF",
              "func" : RRE_R },
   0xe336 : { "name" : "PFD",
              "func" : RXY_M },
   0xb218 : { "name" : "PC",
              "func" : S },
   0x0101 : { "name" : "PR",
              "func" : E },
   0xb228 : { "name" : "PT",
              "func" : RRE },
   0xb99e : { "name" : "PTI",
              "func" : RRE },
   0xb248 : { "name" : "PALB",
              "func" : RRE_N },
   0xb20d : { "name" : "PTLB",
              "func" : S_I },
   0xb3fd : { "name" : "QAXTR",
              "func" : RRF_RM },
   0xb3f5 : { "name" : "QADTR",
              "func" : RRF_RM },
   0xb3ff : { "name" : "RRXTR",
              "func" : RRF_RM },
   0xb3f7 : { "name" : "RRDTR",
              "func" : RRF_RM },
   0xb23b : { "name" : "RCHP",
              "func" : S_I },
   0xb22a : { "name" : "RRBE",
              "func" : RRE },
   0xb277 : { "name" : "RP",
              "func" : S },
   0xb238 : { "name" : "RSCH",
              "func" : S_I },
   0xeb1d : { "name" : "RLL",
              "func" : RSY },
   0xeb1c : { "name" : "RLLG",
              "func" : RSY },
   0xec54 : { "name" : "RNSBG",
              "func" : RIE_RI },
   0xec57 : { "name" : "RXSBG",
              "func" : RIE_RI },
   0xec55 : { "name" : "RISBG",
              "func" : RIE_RI },
   0xec56 : { "name" : "ROSBG",
              "func" : RIE_RI },
   0xb25e : { "name" : "SRST",
              "func" : RRE },
   0xb9be : { "name" : "SRSTU",
              "func" : RRE },
   0xb24e : { "name" : "SAR",
              "func" : RRE },
   0xb237 : { "name" : "SAL",
              "func" : S_I },
   0xb219 : { "name" : "SAC",
              "func" : S },
   0xb279 : { "name" : "SACF",
              "func" : S },
   0x010c : { "name" : "SAM24",
              "func" : E },
   0x010d : { "name" : "SAM31",
              "func" : E },
   0x010e : { "name" : "SAM64",
              "func" : E },
   0xb299 : { "name" : "SRNM",
              "func" : S },
   0xb23c : { "name" : "SCHM",
              "func" : S_I },
   0xb204 : { "name" : "SCK",
              "func" : S },
   0xb206 : { "name" : "SCKC",
              "func" : S },
   0x0107 : { "name" : "SCKPF",
              "func" : E },
   0xb208 : { "name" : "SPT",
              "func" : S },
   0xb2b9 : { "name" : "SRNMT",
              "func" : S },
   0xb384 : { "name" : "SFPC",
              "func" : RRE_R },
   0xb385 : { "name" : "SFASR",
              "func" : RRE_R },
   0xb210 : { "name" : "SPX",
              "func" : S },
   0xb20a : { "name" : "SPKA",
              "func" : S },
   0xb225 : { "name" : "SSAR",
              "func" : RRE_R },
   0xb99f : { "name" : "SSAIR",
              "func" : RRE_R },
   0xb22b : { "name" : "SSKE",
              "func" : RRF_RRM },
   0xeb0b : { "name" : "SLAG",
              "func" : RSY },
   0xeb0d : { "name" : "SLLG",
              "func" : RSY },
   0xeb0a : { "name" : "SRAG",
              "func" : RSY },
   0xeb0c : { "name" : "SRLG",
              "func" : RSY },
   0xed48 : { "name" : "SLXT",
              "func" : RXF },
   0xed40 : { "name" : "SLDT",
              "func" : RXF },
   0xed49 : { "name" : "SLXT",
              "func" : RXF },
   0xed41 : { "name" : "SRDT",
              "func" : RXF },
   0xb316 : { "name" : "SQXBR",
              "func" : RRE },
   0xb336 : { "name" : "SQXR",
              "func" : RRE },
   0xed15 : { "name" : "SQDB",
              "func" : RXE },
   0xb315 : { "name" : "SQDBR",
              "func" : RRE },
   0xed35 : { "name" : "SQD",
              "func" : RXE },
   0xb244 : { "name" : "SQDR",
              "func" : RRE },
   0xed14 : { "name" : "SQEB",
              "func" : RXE },
   0xb314 : { "name" : "SQEBR",
              "func" : RRE },
   0xed34 : { "name" : "SQE",
              "func" : RXE },
   0xb245 : { "name" : "SQER",
              "func" : RRE },
   0xb233 : { "name" : "SSCH",
              "func" : S },
   0xe350 : { "name" : "STY",
              "func" : RXY },
   0xe324 : { "name" : "STG",
              "func" : RXY },
   0xed67 : { "name" : "STDY",
              "func" : RXY },
   0xed66 : { "name" : "STEY",
              "func" : RXY },
   0xb23a : { "name" : "STCPS",
              "func" : S },
   0xb239 : { "name" : "STCRW",
              "func" : S },
   0xe372 : { "name" : "STCY",
              "func" : RXY },
   0xeb2c : { "name" : "STCMH",
              "func" : RSY },
   0xeb2d : { "name" : "STCMY",
              "func" : RSY },
   0xb205 : { "name" : "STCK",
              "func" : S },
   0xb207 : { "name" : "STCKC",
              "func" : S },
   0xb278 : { "name" : "STCKE",
              "func" : S },
   0xb27c : { "name" : "STCKF",
              "func" : S },
   0xeb25 : { "name" : "STCTG",
              "func" : RSY },
   0xb212 : { "name" : "STAP",
              "func" : S },
   0xb202 : { "name" : "STIDP",
              "func" : S },
   0xb209 : { "name" : "STPT",
              "func" : S },
   0xb2b1 : { "name" : "STFL",
              "func" : S },
   0xb2b0 : { "name" : "STFLE",
              "func" : S },
   0xb29c : { "name" : "STFPC",
              "func" : S },
   0xe370 : { "name" : "STHY",
              "func" : RXY },
   0xeb90 : { "name" : "STMY",
              "func" : RSY },
   0xeb24 : { "name" : "STMG",
              "func" : RSY },
   0xeb26 : { "name" : "STMH",
              "func" : RSY },
   0xe38e : { "name" : "STPQ",
              "func" : RXY },
   0xb211 : { "name" : "STPX",
              "func" : S },
   0xe502 : { "name" : "STRAG",
              "func" : SSE },
   0xe33f : { "name" : "STRVH",
              "func" : RXY },
   0xe33e : { "name" : "STRV",
              "func" : RXY },
   0xe32f : { "name" : "STRVG",
              "func" : RXY },
   0xb234 : { "name" : "STSCH",
              "func" : S },
   0xb27d : { "name" : "STSI",
              "func" : S },
   0xb246 : { "name" : "STURA",
              "func" : RRE },
   0xb925 : { "name" : "STURG",
              "func" : RRE },
   0xe35b : { "name" : "SY",
              "func" : RXY },
   0xe309 : { "name" : "SG",
              "func" : RXY },
   0xb909 : { "name" : "SGR",
              "func" : RRE },
   0xe319 : { "name" : "SGF",
              "func" : RXY },
   0xb919 : { "name" : "SGFR",
              "func" : RRE },
   0xb34b : { "name" : "SXBR",
              "func" : RRE },
   0xb3db : { "name" : "SXTR",
              "func" : RRR },
   0xed1b : { "name" : "SDB",
              "func" : RXE },
   0xb31b : { "name" : "SDBR",
              "func" : RRE },
   0xb3d3 : { "name" : "SDTR",
              "func" : RRR },
   0xed0b : { "name" : "SEB",
              "func" : RXE },
   0xb30b : { "name" : "SEBR",
              "func" : RRE },
   0xe37b : { "name" : "SHY",
              "func" : RXY },
   0xe35f : { "name" : "SLY",
              "func" : RXY },
   0xe30b : { "name" : "SLG",
              "func" : RXY },
   0xb90b : { "name" : "SLGR",
              "func" : RRE },
   0xe31b : { "name" : "SLGF",
              "func" : RXY },
   0xb91b : { "name" : "SLGFR",
              "func" : RRE },
   0xe399 : { "name" : "SLB",
              "func" : RXY },
   0xb999 : { "name" : "SLBR",
              "func" : RRE },
   0xe389 : { "name" : "SLBG",
              "func" : RXY },
   0xb989 : { "name" : "SLBGR",
              "func" : RRE },
   0xb2ac : { "name" : "TAR",
              "func" : RRE },
   0x010b : { "name" : "TAM",
              "func" : E },
   0xb22c : { "name" : "TB",
              "func" : RRE },
   0xed12 : { "name" : "TCXB",
              "func" : RXE },
   0xed58 : { "name" : "TDCXT",
              "func" : RXE },
   0xed11 : { "name" : "TCDB",
              "func" : RXE },
   0xed54 : { "name" : "TDCDT",
              "func" : RXE },
   0xed10 : { "name" : "TDEB",
              "func" : RXE },
   0xed50 : { "name" : "TDCET",
              "func" : RXE },
   0xed59 : { "name" : "TDGXT",
              "func" : RXE },
   0xed55 : { "name" : "TDGDT",
              "func" : RXE },
   0xed51 : { "name" : "TDGET",
              "func" : RXE },
   0xebc0 : { "name" : "TP",
              "func" : RSL },
   0xb236 : { "name" : "TPI",
              "func" : S },
   0xe501 : { "name" : "TPROT",
              "func" : SSE },
   0xb235 : { "name" : "TSCH",
              "func" : S },
   0xeb51 : { "name" : "TMY",
              "func" : SIY },
   0xeb0f : { "name" : "TRACG",
              "func" : RSY },
   0xb9bf : { "name" : "TRTE",
              "func" : RRF_RRM },
   0xb9bd : { "name" : "TRTRE",
              "func" : RRF_RRM },
   0xb2a5 : { "name" : "TRE",
              "func" : RRE },
   0xb993 : { "name" : "TROO",
              "func" : RRF_RRM },
   0xb992 : { "name" : "TROT",
              "func" : RRF_RRM },
   0xb991 : { "name" : "TRTO",
              "func" : RRF_RRM },
   0xb990 : { "name" : "TRTT",
              "func" : RRF_RRM },
   0x01ff : { "name" : "TRAP2",
              "func" : E },
   0xb2ff : { "name" : "TRAP4",
              "func" : S },
   0x0102 : { "name" : "UPT",
              "func" : E },
   0xb3f6 : { "name" : "IEDTR",
              "func" : RRF_R },
   0xb3d6 : { "name" : "LTDTR",
              "func" : RRE },
   0xeb9b : { "name" : "STAMY",
              "func" : RSY }
}

# @fn	 getInst
# @brief Given a Mnemonic get the entry from the dictionary. If the entry is
#        found then a base entry is returned.
def getInst( mn ):
   inst = { "name" : "???", "func" : None }
   
   if mn in zos_2byte_mnemonics:
      inst = zos_2byte_mnemonics.get( mn )
   elif mn in zos_3byte_mnemonics:
      inst = zos_3byte_mnemonics.get( mn )
   elif mn in zos_4byte_mnemonics:
      inst = zos_4byte_mnemonics.get( mn )
   
   return( inst )
